TABLE Order {
  order_id SERIAL [primary key]
  order_date DATE [not null]
  price DOUBLE [not null]
}


TABLE Customer {
  customer_id SERIAL [primary key]
  name VARCHAR(50)
  address VARCHAR(100)
}


TABLE Product {
  product_id SERIAL [primary key]
  name VARCHAR(50) [not null]
  quality INTEGER [not null]
}


TABLE CustomerOrder {
  order_id INTEGER [not null, ref: > Order.order_id]
  product_id INETGER [not null, ref: > Product.product_id]
  indexes {
    (order_id, product_id) [pk]
  }
} 


TABLE CustomerProduct {
  customer_id INTEGER [not null, ref: > Customer.customer_id]
  product_id INTEGER [not null, ref: > Product.product_id]
}